"""removed the taxid column

Revision ID: 35a49fa8ce43
Revises: c68155c3e88d
Create Date: 2019-04-13 22:58:47.229605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a49fa8ce43'
down_revision = 'c68155c3e88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism_article', sa.Column('organism_id', sa.Integer(), nullable=True))
    op.drop_constraint('organism_article_organism_taxid_fkey', 'organism_article', type_='foreignkey')
    op.drop_column('organism_article', 'organism_taxid')
    op.drop_column('organisms', 'taxid')
    op.add_column('organisms', sa.Column('id', sa.Integer(), nullable=False))
    op.create_primary_key("organisms_id_pkey", "organisms", ["id"])
    op.create_foreign_key('organism_article_organism_id_fkey', 'organism_article', 'organisms', ['organism_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organism_article_organism_id_fkey', 'organism_article', type_='foreignkey')
    op.drop_column('organism_article', 'organism_id')
    op.drop_constraint('organisms_id_pkey', 'organisms', type_='primary')
    op.drop_column('organisms', 'id')
    op.add_column('organisms', sa.Column('taxid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('organism_article', sa.Column('organism_taxid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('organism_article_organism_taxid_fkey', 'organism_article', 'organisms', ['organism_taxid'], ['taxid'])
    # ### end Alembic commands ###
