"""added sentence foreign key to the organism-article table

Revision ID: 4fde8ccb7856
Revises: 17e7be3fb9f7
Create Date: 2019-04-14 16:36:09.441864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fde8ccb7856'
down_revision = '17e7be3fb9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism_article', sa.Column('sentence_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organism_article', 'sentences', ['sentence_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organism_article', type_='foreignkey')
    op.drop_column('organism_article', 'sentence_id')
    # ### end Alembic commands ###
