"""added bigrams table

Revision ID: 8c335d34fddd
Revises: c0c56b4c922d
Create Date: 2019-04-16 17:26:50.185060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c335d34fddd'
down_revision = 'c0c56b4c922d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bigrams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('tfdif', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bigrams_text'), 'bigrams', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bigrams_text'), table_name='bigrams')
    op.drop_table('bigrams')
    # ### end Alembic commands ###
