"""fixed column name typo

Revision ID: bb67678c8fa2
Revises: 8c335d34fddd
Create Date: 2019-04-16 18:42:27.303867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb67678c8fa2'
down_revision = '8c335d34fddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bigrams', column_name='tfdif', new_column_name='tfidf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bigrams', column_name='tfidf', new_column_name='tfdif')
    # ### end Alembic commands ###
