"""added wiki link table

Revision ID: c0c56b4c922d
Revises: 4fde8ccb7856
Create Date: 2019-04-15 05:04:04.175728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c56b4c922d'
down_revision = '4fde8ccb7856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organism_wikis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organism_id', sa.Integer(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['organisms.id'], ),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organisms', sa.Column('wikiurl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisms', 'wikiurl')
    op.drop_table('organism_wikis')
    # ### end Alembic commands ###
